version: '3.8'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "8000:8000"
  
  app2:
    build:
      context: ./app2
    ports:
      - "8001:8000"

  app3:
    build:
      context: ./app3
    ports:
      - "8002:8000"

networks:
  default:
    driver: bridge